spring:
  datasource:
    url: jdbc:mysql://localhost:3306/login_app
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.springbootlogin.app.domain

server:
  port: 8080
